### ISSUE TITLE
收不到資料

### ISSUE THREAD

**Issue by kobenein** [sintrb/Android-PL2303HXA#1]
有看到
001 當前PL2303HXA設備
002 1002
003 打開串口
004 開始接收

但一直沒看到UART吐的訊息

**Comment by sintrb** [comment]
前两条表明已经正常的识别到PL2303了。
想知道你是如何测试的，波特率和你的通信设备一直了没有？
建议你将你的PL2303设备的TX和RX短接，打开串口后使用app的发送按钮做回环测试，如果app能够收到发出去的数据那么说明设备和驱动都没有问题。
最后，你得再次确认一下你的PL2303的确是PL2303HXA么，这个库只能支出HXA系列的设备。
